apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec: 
  # PersistentVolume name
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # counter part capacity of pv's spec
      # multi claim을 사용하는 경우 PV의 capacity를 넘어가게 요청하면 에러가 발생한다.
      storage: 1Gi