apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec: 
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem # Block, or FileSystem
  accessModes:
    - ReadWriteOnce # SingleNode
    # - ReadOnlyMany, Multiple Node
    # - ReadWriteMany 
  hostPath: 
    path: /data
    type: DirectoryOrCreate