apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template: 
    metadata:
      labels:
        app: frontend 
    spec:
      containers: 
        - name: frontend
          image: opop3966/kub-demo-frontend:latest