apiVersion: v1 # different with deployment.yml
kind: Service
metadata: 
  name: backend
spec: 
  # deployment와 다르게 다르게 예전 방식을 사용하기 때문에 조금 다르다.
  selector: 
    app: second-app
    # tier: backend, 다른 Pod들이 tier: backend 정보를 가지고 있더라도 app: second-app 정보를 가진 Pods들을 노출한다. 
  ports: 
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 127.0.0.1
# kubectl apply -f service.yml
# kubectl delete -f service.yml